# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "myaccount"
user = "myuser"
password = "mypassword"
role = "HOL_ROLE"
warehouse = "HOL_WH"
database = "HOL_DB"
schema = "ANALYTICS"
