snowsql_config_path = "~/.snowsql/config"
snowsql_connection_name = "dev"

[default]
input_parameters = "()"
return_type = "string"
file = "app.zip"
name = "daily_city_metrics_update_sp"
handler = "app.main"
execute_as_caller = true

[dev]
database = "HOL_DB"
schema = "ANALYTICS"
warehouse = "HOL_WH"
role = "HOL_ROLE"
overwrite = true
